export const INIT_ADD_TO_CART = "INIT_ADD_TO_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const FETCH_PRODUCTS = "LOADING_PRODUCTS";
export const INIT_FETCH_PRODUCTS = "INIT_FETCH_PRODUCTS";
export const UPDATE_CART = "UPDATE_CART";
